<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SusunanOrganisasiSeeder extends Seeder
{
    public function run()
    {
        DB::table('susunan_organisasi')->insert([
            [
                'id_susunan_organisasi' => 1,
                'nama_susunan_organisasi' => 'Kepala Dinas',
                'id_susunan_organisasi_parent' => 1,
                'slug_susunan_organisasi' => 'kepala-dinas',
                'tupoksi_susunan_organisasi' => '<div>-</div>',
                'deskripsi_susunan_organisasi' => 'Kami menampilkan informasi dalam bentuk Pelayanan E-Goverment sehingga seluruh masyarakat dapat mengakses data terkait perdagangan.',
                'kelompok_susunan_organisasi' => 'Kepala Dinas',
                'is_subbagian' => 0,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-23 19:52:49',
                'updated_at' => '2025-01-14 01:54:44',
            ],
            [
                'id_susunan_organisasi' => 2,
                'nama_susunan_organisasi' => 'Sekretariat',
                'id_susunan_organisasi_parent' => 1,
                'slug_susunan_organisasi' => 'sekretariat',
                'tupoksi_susunan_organisasi' => null,
                'deskripsi_susunan_organisasi' => 'Menyusun koordinasi penyusunan program, mengelola keuangan, kepegawaian kelengkapan kantor, dan administrasi.',
                'kelompok_susunan_organisasi' => 'Sekretariat',
                'is_subbagian' => 0,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-23 19:52:49',
                'updated_at' => '2024-07-23 19:52:49',
            ],
            [
                'id_susunan_organisasi' => 3,
                'nama_susunan_organisasi' => 'Subbagian Program',
                'id_susunan_organisasi_parent' => 2,
                'slug_susunan_organisasi' => 'subbagian-program',
                'tupoksi_susunan_organisasi' => null,
                'deskripsi_susunan_organisasi' => null,
                'kelompok_susunan_organisasi' => 'Sekretariat',
                'is_subbagian' => 1,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-23 19:52:49',
                'updated_at' => '2025-06-29 06:13:55',
            ],
            [
                'id_susunan_organisasi' => 4,
                'nama_susunan_organisasi' => 'Subbagian Umum dan Kepegawaian',
                'id_susunan_organisasi_parent' => 2,
                'slug_susunan_organisasi' => 'subbagian-umum-dan-kepegawaian',
                'tupoksi_susunan_organisasi' => null,
                'deskripsi_susunan_organisasi' => null,
                'kelompok_susunan_organisasi' => 'Sekretariat',
                'is_subbagian' => 1,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-23 19:52:49',
                'updated_at' => '2024-07-23 19:52:49',
            ],
            [
                'id_susunan_organisasi' => 5,
                'nama_susunan_organisasi' => 'Subbagian Keuangan',
                'id_susunan_organisasi_parent' => 2,
                'slug_susunan_organisasi' => 'subbagian-keuangan',
                'tupoksi_susunan_organisasi' => null,
                'deskripsi_susunan_organisasi' => null,
                'kelompok_susunan_organisasi' => 'Sekretariat',
                'is_subbagian' => 1,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-23 19:52:49',
                'updated_at' => '2024-07-23 19:52:49',
            ],
            [
                'id_susunan_organisasi' => 6,
                'nama_susunan_organisasi' => 'Bidang Sumber Daya Air',
                'id_susunan_organisasi_parent' => 1,
                'slug_susunan_organisasi' => 'bidang-sumber-daya-air',
                'tupoksi_susunan_organisasi' => null,
                'deskripsi_susunan_organisasi' => 'Mengelola sumber daya air di berbagai wilayah, termasuk sungai, bendungan, danau, irigasi, dll., untuk konservasi dan kebutuhan kota.',
                'kelompok_susunan_organisasi' => 'Bidang',
                'is_subbagian' => 0,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-23 19:52:49',
                'updated_at' => '2024-07-23 19:52:49',
            ],
            [
                'id_susunan_organisasi' => 7,
                'nama_susunan_organisasi' => 'Bidang Bina Marga',
                'id_susunan_organisasi_parent' => 1,
                'slug_susunan_organisasi' => 'bidang-bina-marga',
                'tupoksi_susunan_organisasi' => null,
                'deskripsi_susunan_organisasi' => 'Memimpin perencanaan, pembangunan, dan preservasi jalan serta jembatan. Termasuk pengamanan, penerangan jalan, dan pengendalian mutu pekerjaan.',
                'kelompok_susunan_organisasi' => 'Bidang',
                'is_subbagian' => 0,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-23 19:52:49',
                'updated_at' => '2025-01-12 23:47:25',
            ],
            [
                'id_susunan_organisasi' => 8,
                'nama_susunan_organisasi' => 'Bidang Cipta Karya',
                'id_susunan_organisasi_parent' => 1,
                'slug_susunan_organisasi' => 'bidang-cipta-karya',
                'tupoksi_susunan_organisasi' => null,
                'deskripsi_susunan_organisasi' => 'Menangani infrastruktur permukiman, bangunan, dan pengelolaan air minum, drainase, air limbah, serta persampahan di kawasan strategis kota.',
                'kelompok_susunan_organisasi' => 'Bidang',
                'is_subbagian' => 0,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-23 19:52:49',
                'updated_at' => '2024-07-23 19:52:49',
            ],
            [
                'id_susunan_organisasi' => 9,
                'nama_susunan_organisasi' => 'Bidang Bina Konstruksi',
                'id_susunan_organisasi_parent' => 1,
                'slug_susunan_organisasi' => 'bidang-bina-konstruksi',
                'tupoksi_susunan_organisasi' => null,
                'deskripsi_susunan_organisasi' => 'Melaksanakan kebijakan dalam pembinaan jasa konstruksi sesuai dengan peraturan perundang-undangan yang berlaku',
                'kelompok_susunan_organisasi' => 'Bidang',
                'is_subbagian' => 0,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-23 19:52:49',
                'updated_at' => '2024-07-23 19:52:49',
            ],
            [
                'id_susunan_organisasi' => 10,
                'nama_susunan_organisasi' => 'Bidang Tata Ruang',
                'id_susunan_organisasi_parent' => 1,
                'slug_susunan_organisasi' => 'bidang-tata-ruang',
                'tupoksi_susunan_organisasi' => null,
                'deskripsi_susunan_organisasi' => 'Menangani perumusan dan pelaksanaan aturan tata ruang sesuai kewenangan Pemerintah Kota berdasarkan perundangan-undangan yang berlaku.',
                'kelompok_susunan_organisasi' => 'Bidang',
                'is_subbagian' => 0,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-23 19:52:49',
                'updated_at' => '2024-07-23 19:52:49',
            ],
            [
                'id_susunan_organisasi' => 11,
                'nama_susunan_organisasi' => 'Bidang Pertanahan',
                'id_susunan_organisasi_parent' => 1,
                'slug_susunan_organisasi' => 'bidang-pertanahan',
                'tupoksi_susunan_organisasi' => null,
                'deskripsi_susunan_organisasi' => 'Melaksanakan koordinasi izin lokasi, redistribusi tanah, pengadaan tanah kosong, ganti rugi tanah, dan perencanaan pengunaan tanah',
                'kelompok_susunan_organisasi' => 'Bidang',
                'is_subbagian' => 0,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-23 19:52:49',
                'updated_at' => '2025-07-04 02:39:54',
            ],
            [
                'id_susunan_organisasi' => 12,
                'nama_susunan_organisasi' => 'UPTD Pengelolaan Air Limbah Domestik',
                'id_susunan_organisasi_parent' => 1,
                'slug_susunan_organisasi' => 'uptd-pengelolaan-air-limbah-domestik',
                'tupoksi_susunan_organisasi' => null,
                'deskripsi_susunan_organisasi' => 'Melaksanakan kegiatan teknis operasional khususnya layanan air limbah domestik.',
                'kelompok_susunan_organisasi' => 'UPTD',
                'is_subbagian' => 0,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-25 15:58:58',
                'updated_at' => '2024-07-25 15:58:58',
            ],
            [
                'id_susunan_organisasi' => 13,
                'nama_susunan_organisasi' => 'UPTD Pemeliharaan Jalan dan Jembatan',
                'id_susunan_organisasi_parent' => 1,
                'slug_susunan_organisasi' => 'uptd-pemeliharaan-jalan-dan-jembatan',
                'tupoksi_susunan_organisasi' => null,
                'deskripsi_susunan_organisasi' => 'Melaksanakan kegiatan teknis operasional khususnya pemeliharaan jalan dan jembatan',
                'kelompok_susunan_organisasi' => 'UPTD',
                'is_subbagian' => 0,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-25 02:10:21',
                'updated_at' => '2024-07-25 02:10:21',
            ],
            [
                'id_susunan_organisasi' => 14,
                'nama_susunan_organisasi' => 'UPTD Pemeliharaan Saluran Drainase dan Irigasi',
                'id_susunan_organisasi_parent' => 1,
                'slug_susunan_organisasi' => 'uptd-pemeliharaan-saluran-drainase-dan-irigasi',
                'tupoksi_susunan_organisasi' => null,
                'deskripsi_susunan_organisasi' => 'Melaksanakan kegiatan teknis operasional khususnya pemeliharaan saluran drainase dan irigasi.',
                'kelompok_susunan_organisasi' => 'UPTD',
                'is_subbagian' => 0,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-25 02:18:34',
                'updated_at' => '2024-07-25 02:18:34',
            ],
            [
                'id_susunan_organisasi' => 15,
                'nama_susunan_organisasi' => 'Subbagian Tata Usaha UPTD Pengelolaan Air dan Limbah Domestik',
                'id_susunan_organisasi_parent' => 12,
                'slug_susunan_organisasi' => 'subbagian-tata-usaha-uptd-pengelolaan-air-dan-limbah-domestik',
                'tupoksi_susunan_organisasi' => null,
                'deskripsi_susunan_organisasi' => null,
                'kelompok_susunan_organisasi' => 'UPTD',
                'is_subbagian' => 1,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-25 02:22:49',
                'updated_at' => '2024-07-25 02:22:49',
            ],
            [
                'id_susunan_organisasi' => 16,
                'nama_susunan_organisasi' => 'Subbagian Tata Usaha UPTD Pemeliharaan Jalan dan Jembatan',
                'id_susunan_organisasi_parent' => 13,
                'slug_susunan_organisasi' => 'subbagian-tata-usaha-uptd-pemeliharaan-jalan-dan-jembatan',
                'tupoksi_susunan_organisasi' => null,
                'deskripsi_susunan_organisasi' => null,
                'kelompok_susunan_organisasi' => 'UPTD',
                'is_subbagian' => 1,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-25 02:37:03',
                'updated_at' => '2024-07-25 02:37:03',
            ],
            [
                'id_susunan_organisasi' => 17,
                'nama_susunan_organisasi' => 'Subbagian Tata Usaha UPTD Pemeliharaan Saluran Drainase dan Irigasi',
                'id_susunan_organisasi_parent' => 14,
                'slug_susunan_organisasi' => 'subbagian-tata-usaha-uptd-pemeliharaan-saluran-drainase-dan-irigasi',
                'tupoksi_susunan_organisasi' => null,
                'deskripsi_susunan_organisasi' => null,
                'kelompok_susunan_organisasi' => 'UPTD',
                'is_subbagian' => 1,
                'is_susunan_organisasi_fungsional' => 0,
                'created_at' => '2024-07-25 02:47:05',
                'updated_at' => '2024-07-25 02:47:05',
            ],
        ]);
    }
}
